name = "silly-sync"
main = "build/worker/shim.mjs"
compatibility_date = "2023-12-01"

[build]
command = "worker-build --release"

[durable_objects]
bindings = [{ name = "SILLY_SYNC", class_name = "SillySync" }]

[[migrations]]
tag = "v1"
new_classes = ["SillySync"]
