name: Build & Deploy
run-name: ${{ github.actor }} is building pax-centuria 🚀
on:
  push:
    branches:
      - main
jobs:
  build_worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Setup rust
        run: rustup toolchain install stable --profile minimal --target wasm32-unknown-unknown
    
      - name: Install worker-build
        run: cargo install -q worker-build

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./backend

  build_frontend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build static page
        working-directory: ./frontend
        run: npm run build

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/dist    

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4